### ISSUE TITLE
iOS9 + Swift 2.0 error

### ISSUE THREAD

**Issue by flocbit** [DahanHu/DHCollectionTableView#3]
Hey,

I was using DHCollectionTableView in my iOS8 (Storyboard) project. 
Since I upgraded to iOS9 + Swift 2.0 following error appears (iOS8 is still working!):

`*** Assertion failure in -[xxx.ForecastIndexedCollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3505.16/UICollectionView.m:1519
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView dataSource is not set'`

Has anyone any ideas or suggestions?
Help would be much appreciated :)

**Comment by Demons-Bee** [comment]
for so many reasons,I have not yet upgrade to iOS9,I'll be fix it, sorry

**Comment by flocbit** [comment]
Found a temporary workaround:

As I expected iOS9 wants data source and delegate set at initialisation. 

Therefore:

``` swift
class DHCollectionTableViewCell: UITableViewCell, UICollectionViewDataSource, UICollectionViewDelegate { }
```

``` swift
override func awakeFromNib() {
     super.awakeFromNib()

     self.collectionView.delegate = self
     self.collectionView.dataSource = self
}
```

``` swift
func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
     return 0
}

func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
     let cell = UICollectionViewCell()
     return cell
}
```

Don't know the impact on memory consumption but for now I'm happy. Hope this helps someone :)

**Comment by Demons-Bee** [comment]
it works
