### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AdventuresOfMar** [DahanHu/DHCollectionTableView#4]
Hello, How can you use another data source that's not in the appDelegate? I set up an array inside the DHCollectionTableViewController file.  let imageIcon = ["1","2","3","4","5","6","7","8","9","10","11","12"] This is used to call images and see the UIImage to act as the image for a UIImageView that's inside the collectionview class. The problem is that I can't use anything apart from your random color generator to act as what's suppose to be in the celll

**Comment by gkye** [comment]
currently having the same problem. Please add more information to the documentation

**Comment by Demons-Bee** [comment]
you should set dataSource array like the format below:  Array<Array<AnyObject>>
[["1","2","3","4","5","6","7","8","9","10","11","12" ], [ "1","2","3","4","5","6","7","8","9","10","11","12"]],
