### ISSUE TITLE
Need json integration

### ISSUE THREAD

**Issue by codeservis** [DahanHu/DHCollectionTableView#7]
Hello great but need json integration can you do some example ? Need to parse every square from web with json api.

Thanks

**Comment by Demons-Bee** [comment]
``` swift```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    self.window = UIWindow(frame: UIScreen.mainScreen().bounds)

    let numberOfTableViewRows: NSInteger = 20
    let numberOfCollectionViewCells: NSInteger = 30

    var source = Array<AnyObject>()
    for _ in 0..<numberOfTableViewRows {
      var colorArray = Array<UIColor>()
      for _ in 0..<numberOfCollectionViewCells {
        let color = UIColor(red: CGFloat(drand48()), green: CGFloat(drand48()), blue: CGFloat(drand48()), alpha: 1)
        colorArray.append(color)
      }
      source.append(colorArray)
    }

    // the source format is Array<Array<AnyObject>>
    let viewController = DHCollectionTableViewController(source: source)
    viewController.title = "TableView嵌套CollectionView"
    window?.rootViewController = UINavigationController(rootViewController: viewController)
    window?.makeKeyAndVisible()
    return true
  }
```

**Comment by Demons-Bee** [comment]
the source format is Array<Array<AnyObject>>

parse your json object to this format will be help
